# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on: [push, pull_request, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
      - name: Python Version
        run: |
          python --version
      - name: Make Rosters Manifest
        run: |
          python ./src/resources/ci/common/prepare_manifest.py
      - name: Cleanup Pages Workspace
        run: |
          find . -name "*.js" -not -path "./src/resources/pages/*" -type f -delete
          find . -name "*.md" -not -path "./src/resources/pages/*" -type f -delete
          find . -name "*.py" -type f -delete
          find . -empty -type d -delete
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1.0.12
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
        if: contains(github.ref, 'main') || contains(github.ref, 'metadata-updates')
